AirlineReservationSystem/Controllers/FlightsController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;

using System.Web.Mvc;

namespace AirlineReservationSystem.Models
{
    [Authorize]
    public class FlightsController : Controller
    {
        //private DbAirline db = new DbAirline();
        IMockFlights db;

        public FlightsController()
        {
            this.db = new IDataFlights();
        }

        public FlightsController(IMockFlights mockDb)
        {
            this.db = mockDb;
        }

        [AllowAnonymous]
        // GET: Flights
        public ActionResult Index()
        {
            ViewBag.Message = "Flights For Reservation";
            var flights = db.Flights.Include(f => f.Jet);
            return View("Index",flights.ToList());
        }

        // GET: Flights/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Flight flight = db.Flights.Find(id);
            Flight flight = db.Flights.SingleOrDefault(f => f.FlightID == id);
            if (flight == null)
            {
                return HttpNotFound();
            }
            
            return View("Details",flight);
        }

        // GET: Flights/Create
        public ActionResult Create()
        {
            ViewBag.Message = "Book Your Flights";
            ViewBag.FlightJetID = new SelectList(db.Jets, "JetID", "JetName");
            return View("Create");
        }

        // POST: Flights/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FlightID,FlightDate,FlightJetID,FlightSource,FlightDestination,FlightTime")] Flight flight)
        {
            if (ModelState.IsValid)
            {
                //db.Flights.Add(flight);
                //db.SaveChanges();
                db.Save(flight);
                return RedirectToAction("Index");
            }

            ViewBag.FlightJetID = new SelectList(db.Jets, "JetID", "JetName", flight.FlightJetID);
            return View("Create",flight);
        }

        // GET: Flights/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Flight flight = db.Flights.Find(id);
            Flight flight = db.Flights.SingleOrDefault(f => f.FlightID == id);
            if (flight == null)
            {
                return HttpNotFound();
            }
            ViewBag.FlightJetID = new SelectList(db.Jets, "JetID", "JetName", flight.FlightJetID);
            return View("Edit",flight);
        }

        // POST: Flights/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "FlightID,FlightDate,FlightJetID,FlightSource,FlightDestination,FlightTime")] Flight flight)
        {
            if (ModelState.IsValid)
            {
                //db.Entry(flight).State = EntityState.Modified;
                //db.SaveChanges();
                db.Save(flight);
                return RedirectToAction("Index");
            }
            ViewBag.FlightJetID = new SelectList(db.Jets, "JetID", "JetName", flight.FlightJetID);
            return View("Edit",flight);
        }

        // GET: Flights/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Flight flight = db.Flights.SingleOrDefault(f => f.FlightID == id);
            if (flight == null)
            {
                return HttpNotFound();
            }
            return View("Delete",flight);
        }

        // POST: Flights/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Flight flight = db.Flights.SingleOrDefault(f => f.FlightID == id);
            //db.Flights.Remove(flight);
            //db.SaveChanges();
            db.Delete(flight);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AirlineReservationSystem/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AirlineReservationSystem.Models;

namespace AirlineReservationSystem.Controllers
{
    [Authorize ]
    public class TicketsController : Controller
    {
        private DbAirline db = new DbAirline();

        // GET: Tickets
        [AllowAnonymous]
        public ActionResult Index()
        {
            var tickets = db.Tickets.Include(t => t.Flight).Include(t => t.Passenger);
            return View(tickets.ToList());
        }

        // GET: Tickets/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Find(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }
            return View(ticket);
        }

        // GET: Tickets/Create
        public ActionResult Create()
        {
            ViewBag.FlightType = new SelectList(db.Flights, "FlightID", "FlightSource");
            ViewBag.PassengerID = new SelectList(db.Passengers, "PassengerID", "PassengerName");
            return View();
        }

        // POST: Tickets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TicketID,TicketType,PassengerID,FlightType")] Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                db.Tickets.Add(ticket);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.FlightType = new SelectList(db.Flights, "FlightID", "FlightSource", ticket.FlightType);
            ViewBag.PassengerID = new SelectList(db.Passengers, "PassengerID", "PassengerName", ticket.PassengerID);
            return View(ticket);
        }

        // GET: Tickets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Find(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }
            ViewBag.FlightType = new SelectList(db.Flights, "FlightID", "FlightSource", ticket.FlightType);
            ViewBag.PassengerID = new SelectList(db.Passengers, "PassengerID", "PassengerName", ticket.PassengerID);
            return View(ticket);
        }

        // POST: Tickets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TicketID,TicketType,PassengerID,FlightType")] Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ticket).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FlightType = new SelectList(db.Flights, "FlightID", "FlightSource", ticket.FlightType);
            ViewBag.PassengerID = new SelectList(db.Passengers, "PassengerID", "PassengerName", ticket.PassengerID);
            return View(ticket);
        }

        // GET: Tickets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Find(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }
            return View(ticket);
        }

        // POST: Tickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ticket ticket = db.Tickets.Find(id);
            db.Tickets.Remove(ticket);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AirlineReservationSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - AirlineReservationSystem</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @*Added background color to navbar*@
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color: dimgray;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("AirReservation", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @*added new navigation panel*@
                <ul class="nav navbar-nav">

                    <li>@Html.ActionLink("Jets", "Index", "Jets")</li>
                    <li>@Html.ActionLink("PlanTrip", "Index", "Flights")</li>
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("View", "Index", "Tickets")</li>
                    }

                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    @*Alert for weather added to check weather before planning trip*@
    <div class="alert alert-danger container text-capitalize text-center" role="alert">
        <i class="glyphicon glyphicon-exclamation-sign"></i>
        <strong>Weather: </strong> <a href="https://www.accuweather.com/en/world-weather" class="alert-link">Travel Weather!! Alert</a>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        @*Footer which will display at the center of page*@
        <footer>
            <div class="footer-copyright text-center py-3">
                © 2019 Copyright: COMP2084 : AirlineResrvationSystem
                <a href="https://github.com/RutviShah2008/"> RutviShah-200390373</a>
            </div>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>